# Generated by Django 4.1.2 on 2022-11-02 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiuBicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilheteclientebicho', models.JSONField()),
                ('data', models.DateField()),
                ('premiu_bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MegaSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('sorteio', models.JSONField()),
                ('ganhador', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JogoBicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('bichos', models.JSONField(choices=[('1,2,3,4', 'Avestruz'), ('5,6,7,8', 'Àguia'), ('9,10,11,12', 'Burro'), ('13,14,15,16', 'Borboleta'), ('17,18,19,20', 'Cachorro'), ('21,22,23,24', 'Cabra'), ('25,26,27,28', 'Carneiro'), ('29,30,31,32', 'Camelo'), ('33,34,35,36', 'Cobra'), ('37,38,39,40', 'Coelho'), ('41,42,43,44', 'Cavalo'), ('45,46,47,48', 'Elefante'), ('49,50,51,52', 'Galo'), ('53,54,55,56', 'Gato'), ('57,58,59,60', 'Jacaré'), ('61,62,63,64', 'Leão'), ('65,66,67,68', 'Macaco'), ('69,70,71,72', 'Porco'), ('73,74,75,76', 'Pavão'), ('77,78,79,80', 'Perú'), ('81,82,83,84', 'Touro'), ('85,86,87,88', 'Tigre'), ('89,90,91,92', 'Urso'), ('93,94,95,96', 'Veado'), ('97,98,99,00', 'Vaca')])),
                ('bilhetecliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_conta', models.CharField(max_length=50)),
                ('carteira', models.FloatField(default=0)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BilheteClienteLoteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilheteclientesena', models.JSONField()),
                ('data', models.DateField()),
                ('bilhete_cliente_mega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
