# Generated by Django 4.1.2 on 2022-10-29 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilheteclienteloteria',
            name='bilhete_cliente_mega',
        ),
        migrations.AlterField(
            model_name='bilheteclienteloteria',
            name='bilheteclientesena',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
