# Generated by Django 4.1.2 on 2022-10-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro_Cliente',
            new_name='Cliente',
        ),
    ]
