# Generated by Django 4.1.2 on 2022-10-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogobicho',
            name='bichos',
            field=models.JSONField(),
        ),
    ]
