# Generated by Django 4.1.2 on 2022-10-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_bilheteclienteloteria_bilhete_cliente_mega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilheteclienteloteria',
            name='bilhete_cliente_mega',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bilheteclienteloteria',
            name='bilheteclientesena',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='premiubicho',
            name='premiu_bilhete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
