# Generated by Django 4.1.2 on 2022-10-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_jogobicho_bichos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogobicho',
            name='bichos',
            field=models.JSONField(choices=[('1,2,3,4', 'Avestruz'), ('5,6,7,8', 'Àguia'), ('9,10,11,12', 'Burro'), ('13,14,15,16', 'Borboleta'), ('17,18,19,20', 'Cachorro'), ('21,22,23,24', 'Cabra'), ('25,26,27,28', 'Carneiro'), ('29,30,31,32', 'Camelo'), ('33,34,35,36', 'Cobra'), ('37,38,39,40', 'Coelho'), ('41,42,43,44', 'Cavalo'), ('45,46,47,48', 'Elefante'), ('49,50,51,52', 'Galo'), ('53,54,55,56', 'Gato'), ('57,58,59,60', 'Jacaré'), ('61,62,63,64', 'Leão'), ('65,66,67,68', 'Macaco'), ('69,70,71,72', 'Porco'), ('73,74,75,76', 'Pavão'), ('77,78,79,80', 'Perú'), ('81,82,83,84', 'Touro'), ('85,86,87,88', 'Tigre'), ('89,90,91,92', 'Urso'), ('93,94,95,96', 'Veado'), ('97,98,99,00', 'Vaca')]),
        ),
    ]
