# Generated by Django 4.1.2 on 2022-10-29 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_bilheteclienteloteria_bilhete_cliente_mega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogobicho',
            name='bilhetecliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
